### PR TITLE
Fix proxy when upstream url has a path

### PR DESCRIPTION
**Pull request by sylr**
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>

### CODE REVIEW

**Comment by prymitive** [comment]
I'm not sure what this is trying to fix just from reading the code, can you explain the problem a bit?

**Comment by sylr** [comment]
Alertmanagers can use -web.route-prefix "<prefix>"  to define a prefix before all the endpoints therefore the proxy should send request to "https://alertmanager/<prefix>" + req.URL.Path

**Comment by prymitive** [comment]
Thanks, I'll look into this in the next few days

**Comment by sylr** [comment]
FYI I've been running this patch on unsee for a while now.

**Comment by prymitive** [comment]
added tests and fixed commit message to make the linter happy - #174

**Pull request closed without merging**
