### PR TITLE
feat(ui): added silenceExistingAlertsOnly option

### PR DESCRIPTION
**Pull request by wimi**
This PR adds additional global flag for Karma settings: silenceExistingAlertsOnly

When enabled, Karma will allow silencing only existing alert instances - that is, adding matchers/modifying existing will be limited and arbitrary silences will be impossible to construct.

We needed this functionality to allow our users monitoring their alerts - fixing problem at source or selective silencing specific alert instances. We didn't want our users to do general alert silencing, which potentially would silence future alerts as well.

Please note: I have not react experience whatsoever, changes are done based on existing code. I am aware that it might not be perfect.

### CODE REVIEW

**Comment by wimi** [comment]
I adjusted/added minimal tests. But build pipeline is still failing for some reason here.

**Comment by milunko** [comment]
We would love to have this feature.

**Comment by prymitive** [comment]
Any new configuration should have a section, rather than being root element. Silence form options should be nested under [silenceForm](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#silence-form).

What does this PR actually do? What happens when this flag is enabled? How do you differentiate between a silence for existing alert and non-existing one?

**Comment by wimi** [comment]
> Any new configuration should have a section, rather than being root element. Silence form options should be nested under [silenceForm](https://github.com/prymitive/karma/blob/master/docs/CONFIGURATION.md#silence-form).
Thanks - haven't noticed that to be honest, I can certainly move the flag into this section.

> What does this PR actually do? What happens when this flag is enabled? How do you differentiate between a silence for existing alert and non-existing one?
When flag is enabled - silence form does not allow you to modify label names/values and add/remove them. Thus - you can only create alert instances which directly correlate to silenced groups (label values that are present when group is silenced). There is no additional logic other than that. Existing alerts are not analyzed in any way. Again - this is to prevent users from creating silences that may silence too much in the future (by accident, not understanding what they do etc). We'd like to give access to Karma to wider audience, not in read-only mode, but also limiting potential errors.

**Comment by prymitive** [comment]
I'll have a look at this when I have some time, thanks

**Comment by prymitive** [comment]
I've looked at this again and it adds some extra complication to the silence form flow (which is already non-trivial). If I open the form everything is grayed out but there are still buttons to submit the form and if you click them you get error messages that matchers are required, but no way to add them.

**Comment by wimi** [comment]
Hi, the only silences that could be created are those related to currently visible alerts. We want users to silence things that are currently present, and those only.
The setting prevents creating arbitrary silences. It is a good idea to hide that global silence button with this option enabled - thanks for pointing this out - it doesn't make sense to show it at all. Completely forgot it exists.

**Pull request closed without merging**
