### PR TITLE
build(ui): switch to yarn & improve docker layers

### PR DESCRIPTION
**Pull request by andsens**
Instead of copying over all of `ui/` at once, copy `yarn.lock` (previously `package-lock.json`) first, install the deps, and *then* copy the source files. This way you do not need to reinstall the dependencies with every change in the code.

I hope it's ok I switched to yarn in the same PR. It's a drop-in replacement really, and it runs faster and more reliably.

### CODE REVIEW

**Comment by andsens** [comment]
welp, I'm guessing the reset of the package locks has something to do with this?

**Comment by prymitive** [comment]
Thanks for the PR but I don't really want to switch to yarn, it requires an extra build tool with non-trivial version pinning (while npm is bundled with node package/docker image) without providing any huge benefits.

**Comment by andsens** [comment]
OK, cool. I would still recommend the dockerfile adjustment though.
Also: You should install using `npm ci`. `npm install` does not respect `package-lock.json`

**Comment by prymitive** [comment]
AFAIR there is a very old yarn in the docker image plus travis CI also uses ancient version without any "standard" way for managing it.

Will look into layers, thanks

**Comment by prymitive** [comment]
Raised #1443 for layers, thanks!

**Pull request closed without merging**
