### PR TITLE
feat(backend): add support for upstream server connection proxy

### PR DESCRIPTION
**Pull request by mhrabovcin**
This change adds an option to configure a proxy server per upstream server.

### CODE REVIEW

**Review by prymitive — APPROVED** [review]

**Comment by prymitive** [comment]
Thanks!

**Comment by hectorj2f** [comment]
Awesome

**Comment by hectorj2f** [comment]
@prymitive Do you have an idea when this change will land into a next release ? Thanks in advance.

**Comment by prymitive** [comment]
There should be one in a few days

**Comment by prymitive** [comment]
v0.81 is out

**Comment by hectorj2f** [comment]
Thanks @prymitive 🎉

**Pull request merged**
